/** Curated demo seed of common Thai OTC / pharmacy brands — not the official NLEM. */
export const thaiCommonMedicines = [
  { name: "Sara", aliases: ["ซาร่า", "sara"], generic: "paracetamol", form: "tablet" },
  { name: "Tylenol", aliases: ["tylenol"], generic: "paracetamol", form: "tablet" },
  { name: "Paracetamol", aliases: ["พาราเซตามอล", "acetaminophen", "para"], generic: "paracetamol", form: "tablet" },
  { name: "Tiffy", aliases: ["ทิฟฟี่", "tiffy"], generic: "paracetamol chlorpheniramine", form: "tablet" },
  { name: "Decolgen", aliases: ["ดีคอลเจน", "decolgen"], generic: "paracetamol", form: "tablet" },
  { name: "Stream", aliases: ["สตรีม", "stream"], generic: "paracetamol", form: "tablet" },
  { name: "Boska", aliases: ["บอสก้า", "boska"], generic: "ibuprofen", form: "tablet" },
  { name: "Nurofen", aliases: ["นูโรเฟน", "nurofen"], generic: "ibuprofen", form: "tablet" },
  { name: "Brufen", aliases: ["บรูเฟน", "brufen"], generic: "ibuprofen", form: "tablet" },
  { name: "Ibuprofen", aliases: ["ไอบูโพรเฟน", "ibu"], generic: "ibuprofen", form: "tablet" },
  { name: "Aspirin", aliases: ["แอสไพริน", "asa"], generic: "acetylsalicylic acid", form: "tablet" },
  { name: "Disprin", aliases: ["ดิสพริน", "disprin"], generic: "acetylsalicylic acid", form: "tablet" },
  { name: "Amoxicillin", aliases: ["อะม็อกซิซิลลิน", "amoxil", "amoxy"], generic: "amoxicillin", form: "capsule" },
  { name: "Augmentin", aliases: ["ออคเมนติน", "augmentin"], generic: "amoxicillin clavulanate", form: "tablet" },
  { name: "Cloxacillin", aliases: ["คลอกซาซิลลิน", "cloxa"], generic: "cloxacillin", form: "capsule" },
  { name: "Cefalexin", aliases: ["เซฟาเลซิน", "keflex", "cephalexin"], generic: "cefalexin", form: "capsule" },
  { name: "Metronidazole", aliases: ["เมโทรนิดาโซล", "flagyl"], generic: "metronidazole", form: "tablet" },
  { name: "Omeprazole", aliases: ["โอเมพราโซล", "losec"], generic: "omeprazole", form: "capsule" },
  { name: "Losec", aliases: ["โลเสค", "losec"], generic: "omeprazole", form: "capsule" },
  { name: "Gaviscon", aliases: ["แกวิสคอน", "gaviscon"], generic: "alginate", form: "liquid" },
  { name: "Maalox", aliases: ["มาล็อกซ์", "maalox"], generic: "aluminum magnesium", form: "liquid" },
  { name: "Buscopan", aliases: ["บัสโคแพน", "buscopan"], generic: "hyoscine", form: "tablet" },
  { name: "Motilium", aliases: ["โมทิเลียม", "motilium"], generic: "domperidone", form: "tablet" },
  { name: "Domperidone", aliases: ["โดมเพอริโดน"], generic: "domperidone", form: "tablet" },
  { name: "Loratadine", aliases: ["ลอราทาดีน", "clarityne", "claritin"], generic: "loratadine", form: "tablet" },
  { name: "Clarityne", aliases: ["คลาริทีน", "clarityne"], generic: "loratadine", form: "tablet" },
  { name: "Cetirizine", aliases: ["เซทิริซีน", "zyrtec"], generic: "cetirizine", form: "tablet" },
  { name: "Chlorpheniramine", aliases: ["คลอเฟนิรามีน", "cpm"], generic: "chlorpheniramine", form: "tablet" },
  { name: "Dimetapp", aliases: ["ไดเมทับ", "dimetapp"], generic: "brompheniramine", form: "liquid" },
  { name: "Bisolvon", aliases: ["ไบซอลวอน", "bisolvon"], generic: "bromhexine", form: "tablet" },
  { name: "Robitussin", aliases: ["โรบิทัสซิน", "robitussin"], generic: "dextromethorphan", form: "liquid" },
  { name: "Dextromethorphan", aliases: ["เด็กซ์โทรเมทอร์แฟน", "dm"], generic: "dextromethorphan", form: "liquid" },
  { name: "Salbutamol", aliases: ["ซัลบูทามอล", "ventolin"], generic: "salbutamol", form: "inhaler" },
  { name: "Ventolin", aliases: ["เวนโทลิน", "ventolin"], generic: "salbutamol", form: "inhaler" },
  { name: "Berodual", aliases: ["บีโรดูอัล", "berodual"], generic: "ipratropium fenoterol", form: "inhaler" },
  { name: "Prednisolone", aliases: ["เพรดนิโซโลน", "pred"], generic: "prednisolone", form: "tablet" },
  { name: "Dexamethasone", aliases: ["เดกซาเมทาโซน", "dexa"], generic: "dexamethasone", form: "tablet" },
  { name: "Metformin", aliases: ["เมทฟอร์มิน", "glucophage"], generic: "metformin", form: "tablet" },
  { name: "Amlodipine", aliases: ["แอมโลดิพีน", "norvasc"], generic: "amlodipine", form: "tablet" },
  { name: "Losartan", aliases: ["โลซาร์แทน", "cozaar"], generic: "losartan", form: "tablet" },
  { name: "Atorvastatin", aliases: ["อะทอร์วาสแตติน", "lipitor"], generic: "atorvastatin", form: "tablet" },
  { name: "Simvastatin", aliases: ["ซิมวาสแตติน", "zocor"], generic: "simvastatin", form: "tablet" },
  { name: "Vitamin C", aliases: ["วิตามินซี", "ascorbic", "vit c"], generic: "ascorbic acid", form: "tablet" },
  { name: "Vitamin B Complex", aliases: ["วิตามินบี", "b complex", "becozyme"], generic: "vitamin b", form: "tablet" },
  { name: "Calcium", aliases: ["แคลเซียม", "caltrate"], generic: "calcium", form: "tablet" },
  { name: "ORS", aliases: ["โออาร์เอส", "oral rehydration", "electrolyte"], generic: "oral rehydration salts", form: "powder" },
  { name: "Betadine", aliases: ["เบตาดีน", "betadine", "povidone"], generic: "povidone iodine", form: "liquid" },
  { name: "Bactroban", aliases: ["แบคโทรแบน", "bactroban", "mupirocin"], generic: "mupirocin", form: "cream" },
  { name: "Hydrocortisone", aliases: ["ไฮโดรคอร์ติโซน", "hc cream"], generic: "hydrocortisone", form: "cream" },
  { name: "Diclofenac", aliases: ["ไดโคลฟีแนค", "voltarol", "voltaren"], generic: "diclofenac", form: "tablet" },
  { name: "Mefenamic acid", aliases: ["กรดเมฟีนามิก", "ponstan"], generic: "mefenamic acid", form: "capsule" },
  { name: "Ponstan", aliases: ["พอนสแตน", "ponstan"], generic: "mefenamic acid", form: "capsule" }
];
